// Code generated by protoc-gen-goten-resource
// Resource: Agent
// DO NOT EDIT!!!

package agent

import (
	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"
)

// proto imports
import (
	ntt_meta "github.com/cloudwan/edgelq-sdk/common/types/meta"
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
)

// ensure the imports are used
var (
	_ = gotenobject.FieldPath(nil)
	_ = gotenresource.ListQuery(nil)
)

// make sure we're using proto imports
var (
	_ = &ntt_meta.Meta{}
	_ = &iam_project.Project{}
)

var (
	descriptor = &Descriptor{
		typeName: gotenresource.NewTypeName(
			"Agent", "Agents", "workplace.edgelq.com"),
		nameDescriptor: gotenresource.NewNameDescriptor(
			&Agent_FieldTerminalPath{selector: Agent_FieldPathSelectorName},
			"pattern", "agentId",
			[]string{"projectId"},
			[]gotenresource.NamePattern{NamePattern_Project}),
	}
)

type Descriptor struct {
	nameDescriptor *gotenresource.NameDescriptor
	typeName       *gotenresource.TypeName
}

func GetDescriptor() *Descriptor {
	return descriptor
}

func (d *Descriptor) NewAgent() *Agent {
	return &Agent{}
}

func (d *Descriptor) NewResource() gotenresource.Resource {
	return d.NewAgent()
}

func (d *Descriptor) NewResourceName() gotenresource.Name {
	return NewNameBuilder().Name()
}

func (d *Descriptor) NewAgentName() *Name {
	return NewNameBuilder().Name()
}

func (d *Descriptor) NewGetQuery() gotenresource.GetQuery {
	return &GetQuery{}
}

func (d *Descriptor) NewListQuery() gotenresource.ListQuery {
	return &ListQuery{}
}

func (d *Descriptor) NewSearchQuery() gotenresource.SearchQuery {
	return nil
}

func (d *Descriptor) NewWatchQuery() gotenresource.WatchQuery {
	return &WatchQuery{}
}
func (d *Descriptor) NewAgentCursor() *PagerCursor {
	return &PagerCursor{}
}

func (d *Descriptor) NewResourceCursor() gotenresource.Cursor {
	return d.NewAgentCursor()
}
func (d *Descriptor) NewAgentChange() *AgentChange {
	return &AgentChange{}
}

func (d *Descriptor) NewResourceChange() gotenresource.ResourceChange {
	return d.NewAgentChange()
}

func (d *Descriptor) NewAgentQueryResultSnapshot() *QueryResultSnapshot {
	return &QueryResultSnapshot{}
}

func (d *Descriptor) NewQueryResultSnapshot() gotenresource.QueryResultSnapshot {
	return d.NewAgentQueryResultSnapshot()
}
func (d *Descriptor) NewAgentQueryResultChange() *QueryResultChange {
	return &QueryResultChange{}
}

func (d *Descriptor) NewSearchQueryResultSnapshot() gotenresource.SearchQueryResultSnapshot {
	return nil
}

func (d *Descriptor) NewQueryResultChange() gotenresource.QueryResultChange {
	return d.NewAgentQueryResultChange()
}

func (d *Descriptor) NewAgentList(size, reserved int) AgentList {
	return make(AgentList, size, reserved)
}

func (d *Descriptor) NewResourceList(size, reserved int) gotenresource.ResourceList {
	return make(AgentList, size, reserved)
}
func (d *Descriptor) NewAgentChangeList(size, reserved int) AgentChangeList {
	return make(AgentChangeList, size, reserved)
}

func (d *Descriptor) NewResourceChangeList(size, reserved int) gotenresource.ResourceChangeList {
	return make(AgentChangeList, size, reserved)
}

func (d *Descriptor) NewAgentNameList(size, reserved int) AgentNameList {
	return make(AgentNameList, size, reserved)
}

func (d *Descriptor) NewNameList(size, reserved int) gotenresource.NameList {
	return make(AgentNameList, size, reserved)
}

func (d *Descriptor) NewAgentReferenceList(size, reserved int) AgentReferenceList {
	return make(AgentReferenceList, size, reserved)
}

func (d *Descriptor) NewReferenceList(size, reserved int) gotenresource.ReferenceList {
	return make(AgentReferenceList, size, reserved)
}
func (d *Descriptor) NewAgentParentNameList(size, reserved int) AgentParentNameList {
	return make(AgentParentNameList, size, reserved)
}

func (d *Descriptor) NewParentNameList(size, reserved int) gotenresource.ParentNameList {
	return make(AgentParentNameList, size, reserved)
}
func (d *Descriptor) NewAgentParentReferenceList(size, reserved int) AgentParentReferenceList {
	return make(AgentParentReferenceList, size, reserved)
}

func (d *Descriptor) NewParentReferenceList(size, reserved int) gotenresource.ParentReferenceList {
	return make(AgentParentReferenceList, size, reserved)
}

func (d *Descriptor) NewAgentMap(reserved int) AgentMap {
	return make(AgentMap, reserved)
}

func (d *Descriptor) NewResourceMap(reserved int) gotenresource.ResourceMap {
	return make(AgentMap, reserved)
}
func (d *Descriptor) NewAgentChangeMap(reserved int) AgentChangeMap {
	return make(AgentChangeMap, reserved)
}

func (d *Descriptor) NewResourceChangeMap(reserved int) gotenresource.ResourceChangeMap {
	return make(AgentChangeMap, reserved)
}

func (d *Descriptor) GetResourceTypeName() *gotenresource.TypeName {
	return d.typeName
}

func (d *Descriptor) GetNameDescriptor() *gotenresource.NameDescriptor {
	return d.nameDescriptor
}

func (d *Descriptor) ParseFieldPath(raw string) (gotenobject.FieldPath, error) {
	return ParseAgent_FieldPath(raw)
}

func (d *Descriptor) ParseAgentName(nameStr string) (*Name, error) {
	return ParseName(nameStr)
}

func (d *Descriptor) ParseResourceName(nameStr string) (gotenresource.Name, error) {
	return ParseName(nameStr)
}
