// Code generated by protoc-gen-goten-go
// File: workplace/proto/v1alpha2/device_group_change.proto
// DO NOT EDIT!!!

package device_group

import (
	"fmt"
	"reflect"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	preflect "google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// proto imports
import (
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/project"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = fmt.Errorf
	_ = reflect.Method{}
	_ = sync.Once{}

	_ = protojson.MarshalOptions{}
	_ = proto.MarshalOptions{}
	_ = preflect.Value{}
	_ = protoimpl.DescBuilder{}
)

// make sure we're using proto imports
var (
	_ = &iam_project.Project{}
	_ = &field_mask.FieldMask{}
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceGroupChange is used by Watch notifications Responses to describe change
// of single DeviceGroup One of Added, Modified, Removed
type DeviceGroupChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	// DeviceGroup change
	//
	// Types that are valid to be assigned to ChangeType:
	//	*DeviceGroupChange_Added_
	//	*DeviceGroupChange_Modified_
	//	*DeviceGroupChange_Current_
	//	*DeviceGroupChange_Removed_
	ChangeType isDeviceGroupChange_ChangeType `protobuf_oneof:"change_type"`
}

func (m *DeviceGroupChange) Reset() {
	*m = DeviceGroupChange{}
	if protoimpl.UnsafeEnabled {
		mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		ms.StoreMessageInfo(mi)
	}
}

func (m *DeviceGroupChange) String() string {
	return protoimpl.X.MessageStringOf(m)
}

func (*DeviceGroupChange) ProtoMessage() {}

func (m *DeviceGroupChange) ProtoReflect() preflect.Message {
	mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && m != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(m)
}

func (*DeviceGroupChange) GotenMessage() {}

// Deprecated, Use DeviceGroupChange.ProtoReflect.Descriptor instead.
func (*DeviceGroupChange) Descriptor() ([]byte, []int) {
	return workplace_proto_v1alpha2_device_group_change_proto_rawDescGZIP(), []int{0}
}

func (m *DeviceGroupChange) Unmarshal(b []byte) error {
	return proto.Unmarshal(b, m)
}

func (m *DeviceGroupChange) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *DeviceGroupChange) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{}.Marshal(m)
}

func (m *DeviceGroupChange) UnmarshalJSON(data []byte) error {
	return protojson.Unmarshal(data, m)
}

type isDeviceGroupChange_ChangeType interface {
	isDeviceGroupChange_ChangeType()
}

type DeviceGroupChange_Added_ struct {
	// Added is returned when watched document is added, either created or
	// enters Query view
	Added *DeviceGroupChange_Added `protobuf:"bytes,1,opt,name=added,proto3,oneof" firestore:"added"`
}
type DeviceGroupChange_Modified_ struct {
	// Modified is returned when watched document is modified
	Modified *DeviceGroupChange_Modified `protobuf:"bytes,2,opt,name=modified,proto3,oneof" firestore:"modified"`
}
type DeviceGroupChange_Current_ struct {
	// Current is returned in stateless watch when document enters query view or
	// is modified within.
	Current *DeviceGroupChange_Current `protobuf:"bytes,4,opt,name=current,proto3,oneof" firestore:"current"`
}
type DeviceGroupChange_Removed_ struct {
	// Removed is returned when DeviceGroup is deleted or leaves Query view
	Removed *DeviceGroupChange_Removed `protobuf:"bytes,3,opt,name=removed,proto3,oneof" firestore:"removed"`
}

func (*DeviceGroupChange_Added_) isDeviceGroupChange_ChangeType()    {}
func (*DeviceGroupChange_Modified_) isDeviceGroupChange_ChangeType() {}
func (*DeviceGroupChange_Current_) isDeviceGroupChange_ChangeType()  {}
func (*DeviceGroupChange_Removed_) isDeviceGroupChange_ChangeType()  {}
func (m *DeviceGroupChange) GetChangeType() isDeviceGroupChange_ChangeType {
	if m != nil {
		return m.ChangeType
	}
	return nil
}
func (m *DeviceGroupChange) GetAdded() *DeviceGroupChange_Added {
	if x, ok := m.GetChangeType().(*DeviceGroupChange_Added_); ok {
		return x.Added
	}
	return nil
}
func (m *DeviceGroupChange) GetModified() *DeviceGroupChange_Modified {
	if x, ok := m.GetChangeType().(*DeviceGroupChange_Modified_); ok {
		return x.Modified
	}
	return nil
}
func (m *DeviceGroupChange) GetCurrent() *DeviceGroupChange_Current {
	if x, ok := m.GetChangeType().(*DeviceGroupChange_Current_); ok {
		return x.Current
	}
	return nil
}
func (m *DeviceGroupChange) GetRemoved() *DeviceGroupChange_Removed {
	if x, ok := m.GetChangeType().(*DeviceGroupChange_Removed_); ok {
		return x.Removed
	}
	return nil
}
func (m *DeviceGroupChange) SetChangeType(ofv isDeviceGroupChange_ChangeType) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "isDeviceGroupChange_ChangeType", "DeviceGroupChange"))
	}
	m.ChangeType = ofv
}
func (m *DeviceGroupChange) SetAdded(fv *DeviceGroupChange_Added) {
	m.SetChangeType(&DeviceGroupChange_Added_{Added: fv})
}
func (m *DeviceGroupChange) SetModified(fv *DeviceGroupChange_Modified) {
	m.SetChangeType(&DeviceGroupChange_Modified_{Modified: fv})
}
func (m *DeviceGroupChange) SetCurrent(fv *DeviceGroupChange_Current) {
	m.SetChangeType(&DeviceGroupChange_Current_{Current: fv})
}
func (m *DeviceGroupChange) SetRemoved(fv *DeviceGroupChange_Removed) {
	m.SetChangeType(&DeviceGroupChange_Removed_{Removed: fv})
}

// DeviceGroup has been added to query view
type DeviceGroupChange_Added struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceGroup   *DeviceGroup `protobuf:"bytes,1,opt,name=device_group,json=deviceGroup,proto3" json:"device_group,omitempty" firestore:"deviceGroup"`
	// Integer describing index of added DeviceGroup in resulting query view.
	ViewIndex int32 `protobuf:"varint,2,opt,name=view_index,json=viewIndex,proto3" json:"view_index,omitempty" firestore:"viewIndex"`
}

func (m *DeviceGroupChange_Added) Reset() {
	*m = DeviceGroupChange_Added{}
	if protoimpl.UnsafeEnabled {
		mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		ms.StoreMessageInfo(mi)
	}
}

func (m *DeviceGroupChange_Added) String() string {
	return protoimpl.X.MessageStringOf(m)
}

func (*DeviceGroupChange_Added) ProtoMessage() {}

func (m *DeviceGroupChange_Added) ProtoReflect() preflect.Message {
	mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && m != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(m)
}

func (*DeviceGroupChange_Added) GotenMessage() {}

// Deprecated, Use DeviceGroupChange_Added.ProtoReflect.Descriptor instead.
func (*DeviceGroupChange_Added) Descriptor() ([]byte, []int) {
	return workplace_proto_v1alpha2_device_group_change_proto_rawDescGZIP(), []int{0, 0}
}

func (m *DeviceGroupChange_Added) Unmarshal(b []byte) error {
	return proto.Unmarshal(b, m)
}

func (m *DeviceGroupChange_Added) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *DeviceGroupChange_Added) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{}.Marshal(m)
}

func (m *DeviceGroupChange_Added) UnmarshalJSON(data []byte) error {
	return protojson.Unmarshal(data, m)
}

func (m *DeviceGroupChange_Added) GetDeviceGroup() *DeviceGroup {
	if m != nil {
		return m.DeviceGroup
	}
	return nil
}

func (m *DeviceGroupChange_Added) GetViewIndex() int32 {
	if m != nil {
		return m.ViewIndex
	}
	return int32(0)
}

func (m *DeviceGroupChange_Added) SetDeviceGroup(fv *DeviceGroup) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "DeviceGroup", "DeviceGroupChange_Added"))
	}
	m.DeviceGroup = fv
}

func (m *DeviceGroupChange_Added) SetViewIndex(fv int32) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "ViewIndex", "DeviceGroupChange_Added"))
	}
	m.ViewIndex = fv
}

// DeviceGroup changed some of it's fields - contains either full document or
// masked change
type DeviceGroupChange_Modified struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	// Name of modified DeviceGroup
	Name *Name `protobuf:"bytes,1,opt,customtype=Name,name=name,proto3" json:"name,omitempty" firestore:"name"`
	// New version of DeviceGroup or masked difference, depending on
	// mask_changes instrumentation of issued [WatchDeviceGroupRequest] or
	// [WatchDeviceGroupsRequest]
	DeviceGroup *DeviceGroup `protobuf:"bytes,2,opt,name=device_group,json=deviceGroup,proto3" json:"device_group,omitempty" firestore:"deviceGroup"`
	// Used when mask_changes is set, contains field paths of modified
	// properties.
	FieldMask *DeviceGroup_FieldMask `protobuf:"bytes,3,opt,customtype=DeviceGroup_FieldMask,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty" firestore:"fieldMask"`
	// Previous view index specifies previous position of modified DeviceGroup.
	// When modification doesn't affect sorted order, value will remain
	// identical to [view_index].
	PreviousViewIndex int32 `protobuf:"varint,4,opt,name=previous_view_index,json=previousViewIndex,proto3" json:"previous_view_index,omitempty" firestore:"previousViewIndex"`
	// Integer specifying DeviceGroup new index in resulting query view.
	ViewIndex int32 `protobuf:"varint,5,opt,name=view_index,json=viewIndex,proto3" json:"view_index,omitempty" firestore:"viewIndex"`
}

func (m *DeviceGroupChange_Modified) Reset() {
	*m = DeviceGroupChange_Modified{}
	if protoimpl.UnsafeEnabled {
		mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		ms.StoreMessageInfo(mi)
	}
}

func (m *DeviceGroupChange_Modified) String() string {
	return protoimpl.X.MessageStringOf(m)
}

func (*DeviceGroupChange_Modified) ProtoMessage() {}

func (m *DeviceGroupChange_Modified) ProtoReflect() preflect.Message {
	mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && m != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(m)
}

func (*DeviceGroupChange_Modified) GotenMessage() {}

// Deprecated, Use DeviceGroupChange_Modified.ProtoReflect.Descriptor instead.
func (*DeviceGroupChange_Modified) Descriptor() ([]byte, []int) {
	return workplace_proto_v1alpha2_device_group_change_proto_rawDescGZIP(), []int{0, 1}
}

func (m *DeviceGroupChange_Modified) Unmarshal(b []byte) error {
	return proto.Unmarshal(b, m)
}

func (m *DeviceGroupChange_Modified) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *DeviceGroupChange_Modified) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{}.Marshal(m)
}

func (m *DeviceGroupChange_Modified) UnmarshalJSON(data []byte) error {
	return protojson.Unmarshal(data, m)
}

func (m *DeviceGroupChange_Modified) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *DeviceGroupChange_Modified) GetDeviceGroup() *DeviceGroup {
	if m != nil {
		return m.DeviceGroup
	}
	return nil
}

func (m *DeviceGroupChange_Modified) GetFieldMask() *DeviceGroup_FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *DeviceGroupChange_Modified) GetPreviousViewIndex() int32 {
	if m != nil {
		return m.PreviousViewIndex
	}
	return int32(0)
}

func (m *DeviceGroupChange_Modified) GetViewIndex() int32 {
	if m != nil {
		return m.ViewIndex
	}
	return int32(0)
}

func (m *DeviceGroupChange_Modified) SetName(fv *Name) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "Name", "DeviceGroupChange_Modified"))
	}
	m.Name = fv
}

func (m *DeviceGroupChange_Modified) SetDeviceGroup(fv *DeviceGroup) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "DeviceGroup", "DeviceGroupChange_Modified"))
	}
	m.DeviceGroup = fv
}

func (m *DeviceGroupChange_Modified) SetFieldMask(fv *DeviceGroup_FieldMask) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "FieldMask", "DeviceGroupChange_Modified"))
	}
	m.FieldMask = fv
}

func (m *DeviceGroupChange_Modified) SetPreviousViewIndex(fv int32) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "PreviousViewIndex", "DeviceGroupChange_Modified"))
	}
	m.PreviousViewIndex = fv
}

func (m *DeviceGroupChange_Modified) SetViewIndex(fv int32) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "ViewIndex", "DeviceGroupChange_Modified"))
	}
	m.ViewIndex = fv
}

// DeviceGroup has been added or modified in a query view. Version used for
// stateless watching
type DeviceGroupChange_Current struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	DeviceGroup   *DeviceGroup `protobuf:"bytes,1,opt,name=device_group,json=deviceGroup,proto3" json:"device_group,omitempty" firestore:"deviceGroup"`
}

func (m *DeviceGroupChange_Current) Reset() {
	*m = DeviceGroupChange_Current{}
	if protoimpl.UnsafeEnabled {
		mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		ms.StoreMessageInfo(mi)
	}
}

func (m *DeviceGroupChange_Current) String() string {
	return protoimpl.X.MessageStringOf(m)
}

func (*DeviceGroupChange_Current) ProtoMessage() {}

func (m *DeviceGroupChange_Current) ProtoReflect() preflect.Message {
	mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && m != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(m)
}

func (*DeviceGroupChange_Current) GotenMessage() {}

// Deprecated, Use DeviceGroupChange_Current.ProtoReflect.Descriptor instead.
func (*DeviceGroupChange_Current) Descriptor() ([]byte, []int) {
	return workplace_proto_v1alpha2_device_group_change_proto_rawDescGZIP(), []int{0, 2}
}

func (m *DeviceGroupChange_Current) Unmarshal(b []byte) error {
	return proto.Unmarshal(b, m)
}

func (m *DeviceGroupChange_Current) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *DeviceGroupChange_Current) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{}.Marshal(m)
}

func (m *DeviceGroupChange_Current) UnmarshalJSON(data []byte) error {
	return protojson.Unmarshal(data, m)
}

func (m *DeviceGroupChange_Current) GetDeviceGroup() *DeviceGroup {
	if m != nil {
		return m.DeviceGroup
	}
	return nil
}

func (m *DeviceGroupChange_Current) SetDeviceGroup(fv *DeviceGroup) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "DeviceGroup", "DeviceGroupChange_Current"))
	}
	m.DeviceGroup = fv
}

// Removed is returned when DeviceGroup is deleted or leaves Query view
type DeviceGroupChange_Removed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Name          *Name `protobuf:"bytes,1,opt,customtype=Name,name=name,proto3" json:"name,omitempty" firestore:"name"`
	// Integer specifying removed DeviceGroup index. Not populated in stateless
	// watch type.
	ViewIndex int32 `protobuf:"varint,2,opt,name=view_index,json=viewIndex,proto3" json:"view_index,omitempty" firestore:"viewIndex"`
}

func (m *DeviceGroupChange_Removed) Reset() {
	*m = DeviceGroupChange_Removed{}
	if protoimpl.UnsafeEnabled {
		mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		ms.StoreMessageInfo(mi)
	}
}

func (m *DeviceGroupChange_Removed) String() string {
	return protoimpl.X.MessageStringOf(m)
}

func (*DeviceGroupChange_Removed) ProtoMessage() {}

func (m *DeviceGroupChange_Removed) ProtoReflect() preflect.Message {
	mi := &workplace_proto_v1alpha2_device_group_change_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && m != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(m))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(m)
}

func (*DeviceGroupChange_Removed) GotenMessage() {}

// Deprecated, Use DeviceGroupChange_Removed.ProtoReflect.Descriptor instead.
func (*DeviceGroupChange_Removed) Descriptor() ([]byte, []int) {
	return workplace_proto_v1alpha2_device_group_change_proto_rawDescGZIP(), []int{0, 3}
}

func (m *DeviceGroupChange_Removed) Unmarshal(b []byte) error {
	return proto.Unmarshal(b, m)
}

func (m *DeviceGroupChange_Removed) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *DeviceGroupChange_Removed) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{}.Marshal(m)
}

func (m *DeviceGroupChange_Removed) UnmarshalJSON(data []byte) error {
	return protojson.Unmarshal(data, m)
}

func (m *DeviceGroupChange_Removed) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *DeviceGroupChange_Removed) GetViewIndex() int32 {
	if m != nil {
		return m.ViewIndex
	}
	return int32(0)
}

func (m *DeviceGroupChange_Removed) SetName(fv *Name) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "Name", "DeviceGroupChange_Removed"))
	}
	m.Name = fv
}

func (m *DeviceGroupChange_Removed) SetViewIndex(fv int32) {
	if m == nil {
		panic(fmt.Errorf("can't set %s on nil %s", "ViewIndex", "DeviceGroupChange_Removed"))
	}
	m.ViewIndex = fv
}

var workplace_proto_v1alpha2_device_group_change_proto preflect.FileDescriptor

var workplace_proto_v1alpha2_device_group_change_proto_rawDesc = []byte{
	0x0a, 0x32, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6e, 0x74, 0x74, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x67, 0x6f, 0x74, 0x65, 0x6e,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x6f, 0x74,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x74, 0x65, 0x6e, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2b, 0x77, 0x6f, 0x72, 0x6b,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x32, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x07, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x47, 0x0a,
	0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6e,
	0x74, 0x74, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12, 0x50, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x4d, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6e, 0x74, 0x74, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x32, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x1a, 0x6e, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12,
	0x46, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x69, 0x65,
	0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x9a, 0x02, 0x0a, 0x08, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x13, 0xb2, 0xda, 0x21, 0x0f, 0x0a, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x46, 0x0a, 0x0c,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x4e, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61,
	0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4d, 0x61, 0x73, 0x6b, 0x42, 0x13, 0xb2, 0xda, 0x21, 0x0f, 0x32, 0x0d, 0x0a, 0x0b, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4d, 0x61, 0x73, 0x6b, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x56, 0x69, 0x65, 0x77, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x1a, 0x51, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x46,
	0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x51, 0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x12, 0x27, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x13, 0xb2, 0xda, 0x21, 0x0f, 0x0a, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69,
	0x65, 0x77, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x76, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x3a, 0x11, 0x9a, 0xd9, 0x21, 0x0d, 0x0a,
	0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x0d, 0x0a, 0x0b,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x89, 0x01, 0xe8, 0xde,
	0x21, 0x00, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x42, 0x16, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x00, 0x5a, 0x4a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77, 0x61, 0x6e,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x3b, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	workplace_proto_v1alpha2_device_group_change_proto_rawDescOnce sync.Once
	workplace_proto_v1alpha2_device_group_change_proto_rawDescData = workplace_proto_v1alpha2_device_group_change_proto_rawDesc
)

func workplace_proto_v1alpha2_device_group_change_proto_rawDescGZIP() []byte {
	workplace_proto_v1alpha2_device_group_change_proto_rawDescOnce.Do(func() {
		workplace_proto_v1alpha2_device_group_change_proto_rawDescData = protoimpl.X.CompressGZIP(workplace_proto_v1alpha2_device_group_change_proto_rawDescData)
	})
	return workplace_proto_v1alpha2_device_group_change_proto_rawDescData
}

var workplace_proto_v1alpha2_device_group_change_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var workplace_proto_v1alpha2_device_group_change_proto_goTypes = []interface{}{
	(*DeviceGroupChange)(nil),          // 0: ntt.workplace.v1alpha2.DeviceGroupChange
	(*DeviceGroupChange_Added)(nil),    // 1: ntt.workplace.v1alpha2.DeviceGroupChange.Added
	(*DeviceGroupChange_Modified)(nil), // 2: ntt.workplace.v1alpha2.DeviceGroupChange.Modified
	(*DeviceGroupChange_Current)(nil),  // 3: ntt.workplace.v1alpha2.DeviceGroupChange.Current
	(*DeviceGroupChange_Removed)(nil),  // 4: ntt.workplace.v1alpha2.DeviceGroupChange.Removed
	(*DeviceGroup)(nil),                // 5: ntt.workplace.v1alpha2.DeviceGroup
	(*DeviceGroup_FieldMask)(nil),      // 6: ntt.workplace.v1alpha2.DeviceGroup_FieldMask
}
var workplace_proto_v1alpha2_device_group_change_proto_depIdxs = []int32{
	1, // 0: ntt.workplace.v1alpha2.DeviceGroupChange.added:type_name -> ntt.workplace.v1alpha2.DeviceGroupChange.Added
	2, // 1: ntt.workplace.v1alpha2.DeviceGroupChange.modified:type_name -> ntt.workplace.v1alpha2.DeviceGroupChange.Modified
	3, // 2: ntt.workplace.v1alpha2.DeviceGroupChange.current:type_name -> ntt.workplace.v1alpha2.DeviceGroupChange.Current
	4, // 3: ntt.workplace.v1alpha2.DeviceGroupChange.removed:type_name -> ntt.workplace.v1alpha2.DeviceGroupChange.Removed
	5, // 4: ntt.workplace.v1alpha2.DeviceGroupChange.Added.device_group:type_name -> ntt.workplace.v1alpha2.DeviceGroup
	5, // 5: ntt.workplace.v1alpha2.DeviceGroupChange.Modified.device_group:type_name -> ntt.workplace.v1alpha2.DeviceGroup
	6, // 6: ntt.workplace.v1alpha2.DeviceGroupChange.Modified.field_mask:type_name -> ntt.workplace.v1alpha2.DeviceGroup_FieldMask
	5, // 7: ntt.workplace.v1alpha2.DeviceGroupChange.Current.device_group:type_name -> ntt.workplace.v1alpha2.DeviceGroup
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { workplace_proto_v1alpha2_device_group_change_proto_init() }
func workplace_proto_v1alpha2_device_group_change_proto_init() {
	if workplace_proto_v1alpha2_device_group_change_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {

		workplace_proto_v1alpha2_device_group_change_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceGroupChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		workplace_proto_v1alpha2_device_group_change_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceGroupChange_Added); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		workplace_proto_v1alpha2_device_group_change_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceGroupChange_Modified); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		workplace_proto_v1alpha2_device_group_change_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceGroupChange_Current); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		workplace_proto_v1alpha2_device_group_change_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceGroupChange_Removed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}

	workplace_proto_v1alpha2_device_group_change_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DeviceGroupChange_Added_)(nil),
		(*DeviceGroupChange_Modified_)(nil),
		(*DeviceGroupChange_Current_)(nil),
		(*DeviceGroupChange_Removed_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: workplace_proto_v1alpha2_device_group_change_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           workplace_proto_v1alpha2_device_group_change_proto_goTypes,
		DependencyIndexes: workplace_proto_v1alpha2_device_group_change_proto_depIdxs,
		MessageInfos:      workplace_proto_v1alpha2_device_group_change_proto_msgTypes,
	}.Build()
	workplace_proto_v1alpha2_device_group_change_proto = out.File
	workplace_proto_v1alpha2_device_group_change_proto_rawDesc = nil
	workplace_proto_v1alpha2_device_group_change_proto_goTypes = nil
	workplace_proto_v1alpha2_device_group_change_proto_depIdxs = nil
}
