// Code generated by protoc-gen-goten-client
// Service: Workplace
// DO NOT EDIT!!!

package workplace_client

import (
	"google.golang.org/grpc"
)

// proto imports
import (
	agent_client "github.com/cloudwan/workplace-sdk/client/v1alpha/agent"
	area_client "github.com/cloudwan/workplace-sdk/client/v1alpha/area"
	building_client "github.com/cloudwan/workplace-sdk/client/v1alpha/building"
	device_client "github.com/cloudwan/workplace-sdk/client/v1alpha/device"
	device_group_client "github.com/cloudwan/workplace-sdk/client/v1alpha/device_group"
	floor_client "github.com/cloudwan/workplace-sdk/client/v1alpha/floor"
	property_client "github.com/cloudwan/workplace-sdk/client/v1alpha/property"
	site_client "github.com/cloudwan/workplace-sdk/client/v1alpha/site"
	vendor_connection_client "github.com/cloudwan/workplace-sdk/client/v1alpha/vendor_connection"
	zone_client "github.com/cloudwan/workplace-sdk/client/v1alpha/zone"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = grpc.ClientConn{}
)

// make sure we're using proto imports
var (
	_ = &agent_client.GetAgentRequest{}
	_ = &area_client.GetAreaRequest{}
	_ = &building_client.GetBuildingRequest{}
	_ = &device_group_client.GetDeviceGroupRequest{}
	_ = &device_client.GetDeviceRequest{}
	_ = &floor_client.GetFloorRequest{}
	_ = &property_client.GetPropertyRequest{}
	_ = &site_client.GetSiteRequest{}
	_ = &vendor_connection_client.GetVendorConnectionRequest{}
	_ = &zone_client.GetZoneRequest{}
)

type WorkplaceClient interface {
	agent_client.AgentServiceClient
	area_client.AreaServiceClient
	building_client.BuildingServiceClient
	device_group_client.DeviceGroupServiceClient
	device_client.DeviceServiceClient
	floor_client.FloorServiceClient
	property_client.PropertyServiceClient
	site_client.SiteServiceClient
	vendor_connection_client.VendorConnectionServiceClient
	zone_client.ZoneServiceClient
}

type workplaceClient struct {
	agent_client.AgentServiceClient
	area_client.AreaServiceClient
	building_client.BuildingServiceClient
	device_group_client.DeviceGroupServiceClient
	device_client.DeviceServiceClient
	floor_client.FloorServiceClient
	property_client.PropertyServiceClient
	site_client.SiteServiceClient
	vendor_connection_client.VendorConnectionServiceClient
	zone_client.ZoneServiceClient
}

func NewWorkplaceClient(cc grpc.ClientConnInterface) WorkplaceClient {
	return &workplaceClient{
		AgentServiceClient:            agent_client.NewAgentServiceClient(cc),
		AreaServiceClient:             area_client.NewAreaServiceClient(cc),
		BuildingServiceClient:         building_client.NewBuildingServiceClient(cc),
		DeviceGroupServiceClient:      device_group_client.NewDeviceGroupServiceClient(cc),
		DeviceServiceClient:           device_client.NewDeviceServiceClient(cc),
		FloorServiceClient:            floor_client.NewFloorServiceClient(cc),
		PropertyServiceClient:         property_client.NewPropertyServiceClient(cc),
		SiteServiceClient:             site_client.NewSiteServiceClient(cc),
		VendorConnectionServiceClient: vendor_connection_client.NewVendorConnectionServiceClient(cc),
		ZoneServiceClient:             zone_client.NewZoneServiceClient(cc),
	}
}
